-- Health_Tracker - HT_exercise_library rich seed (idempotent upsert; run after HT_migration.sql)
insert into public.ht_exercise_library (name, activity, sets, reps, description, howto)
values
  ('Push-ups','strength',4,15,'Foundational upper-body push movement. Builds chest, shoulders, triceps and core stability.','Start in a high plank with hands shoulder-width apart. Lower your chest toward the floor keeping a straight line from head to heels, elbows at ~45°. Push back up to full arm extension. Scale down by supporting on knees if needed.'),
  ('Squats (bodyweight)','strength',4,20,'Lower-body strength builder targeting the quads, glutes and hamstrings.','Stand with feet shoulder-width, toes slightly out. Sit the hips back and down as if into a chair, keep the chest up, then drive through the heels to stand. Keep knees tracking over the toes.'),
  ('Lunges','strength',3,15,'Unilateral leg exercise improving single-leg strength, balance and hip stability.','Step forward into a lunge, lowering the back knee toward the floor while the front thigh ends roughly parallel. Push off the front foot to return. Alternate legs each rep.'),
  ('Plank hold','core',3,60,'Isometric core hold building trunk stability and posture endurance.','Assume a forearm plank with elbows under shoulders. Brace the core and glutes so the body forms a straight line from head to heels. Hold for the target time without letting the hips sag.'),
  ('Glute bridge','strength',4,15,'Glute and hamstring activation while reinforcing posterior-chain strength.','Lie on your back, feet flat and hip-width. Drive through the heels to lift the hips until the body forms a line from shoulders to knees, squeeze the glutes at the top, then lower slowly.'),
  ('Burpees','cardio',3,12,'Full-body conditioning and heart-rate builder combining squat, plank and jump.','From standing, squat to the floor, jump or step the feet back to a plank, drop to a push-up (optional), jump the feet back in and leap up with a small jump. Keep it continuous and controlled.'),
  ('Mountain climbers','cardio',4,30,'Dynamic core and cardio move driven by quick alternating knee drives.','From a high plank, drive one knee toward the chest, then switch legs rapidly as if running in place. Keep the hips level and the core braced for the whole set.'),
  ('High knees','cardio',3,45,'Lower-intensity cardio that raises heart rate and improves rhythm.','March or jog on the spot while driving each knee up to hip height. Keep an upright torso and pump the arms in time. Move faster as your form stays consistent.'),
  ('Star jumps','cardio',4,20,'Explosive full-body jump for conditioning, power and mobility.','Start with feet together and arms at your sides. Jump while spreading feet wide and raising both arms overhead to form an X, then land softly and return to the start.'),
  ('Dumbbell goblet squat','strength',4,12,'Weighted squat variation strengthening the legs and upper back.','Hold a dumbbell at your chest with both hands. Squat down with back straight and elbows inside the knees, then drive back up to standing. Keep the weight close to the chest.'),
  ('Dumbbell shoulder press','strength',4,10,'Vertical press building shoulder and upper-arm strength.','Sit or stand with a dumbbell in each hand at shoulder height. Press overhead until the arms are straight, keeping the core braced, then lower back with control.'),
  ('Dumbbell bicep curl','strength',4,12,'Isolates the biceps for arm strength and size.','Stand with a dumbbell in each hand, palms facing forward. Curl the weights toward your shoulders without swinging the elbows, then lower slowly under control.'),
  ('Dumbbell row','strength',4,12,'Horizontal pulling for the back, rear shoulders and grip strength.','Hinge forward with a flat back, holding a dumbbell in each hand. Pull the weights toward your hips, squeezing the shoulder blades, then lower under control.'),
  ('Dumbbell deadlift','strength',4,10,'Hip-hinge strength targeting the posterior chain and grip.','Stand with dumbbells at your thighs. Push the hips back and lower the weights toward the floor, keeping a flat back, then stand tall by driving the hips forward and squeezing glutes.'),
  ('Dumbbell chest press','strength',4,12,'Horizontal press for chest, triceps and shoulder strength.','Lie on a bench holding a dumbbell in each hand above your chest. Lower the weights to the sides of your chest, then press back up to full extension.'),
  ('Dumbbell lateral raise','strength',4,12,'Isolation move for the side deltoids to widen the shoulder line.','Stand with a dumbbell in each hand at your sides. Raise the arms out to the sides till shoulder height, leading with the elbows, then lower slowly without momentum.'),
  ('Dumbbell reverse fly','strength',3,12,'Trains the rear deltoids and upper-back posture muscles.','Hinge forward with a flat back, dumbbells hanging. Open the arms out to the sides keeping a slight elbow bend, then lower with control.'),
  ('Dumbbell tricep extension','strength',3,12,'Extends the triceps straighten to build upper-arm mass.','Hold one dumbbell overhead with both hands. Lower it behind your head by bending the elbows, keeping the elbows pointing up, then extend back overhead.'),
  ('Dumbbell farmer carry','cardio',4,60,'Loaded walk for grip, core and posture endurance and conditioning.','Hold a heavy dumbbell in each hand with shoulders pulled back. Walk upright in a straight line for the allotted time, swapping sides if you go far.'),
  ('Dumbbell renegade row','strength',3,10,'Plank-based row combining core stability with back pulling.','From a high plank with a dumbbell in each hand, row one weight to your ribs while the body stays level, then switch sides after the rep pattern.'),
  ('Bulgarian split squat','strength',3,10,'Single-leg squat building lower-body strength and stability.','Place your rear foot on a bench or surface. Lower straight up and increase the strength of the hips until the front thigh is about level, then drive back up through the front leg alone.'),
  ('Side plank','core',3,40,'Lateral core stability for the obliques and the side body.','Lie on your side propped on your forearm with feet stacked. Lift your hips so the body forms a straight line and hold. Keep the elbow under the shoulder.'),
  ('Dead bug','core',3,12,'Anti-extension core move strengthening the deep core without hip posting.','Lie on your back, arms to the ceiling and knees bent at 90°. Slowly lower the opposite arm and leg toward the floor while keeping the lower back pressed down, then return.'),
  ('Russian twist (weighted)','core',3,20,'Rotational core work for the obliques.','Sit with knees bent and feet hovering. Rotate the torso side to side while holding a weight, tapping the floor beside each hip while keeping the chest lifted.'),
  ('Step-ups','strength',4,12,'Stair-style unilateral leg strength and balance exercise.','Step one foot onto a sturdy surface, drive through that leg to bring the other foot up, then steps. alternate legs and keep the hips square.'),
  ('Calf raises','strength',4,20,'Isolates the calf and soleus for ankle strength and definition.','Stand tall and rise onto the balls of your feet as high as possible, hold briefly, then lower the heels, under control. Add weight in a goblet position to progress.'),
  ('Band pull-apart','mobility',3,15,'Stretches and strengthens the upper back and rear delts for posture.','Hold a light band at chest height with both hands this width. Keeping the arms straight, pull the band outward until the shoulder blades squeeze, then return slowly.'),
  ('Cat-cow stretch','mobility',2,12,'Spinal mobility drill to warm up the back and core.','On all fours, alternate arching the back (cow) and rounding it (cat) by timing the movement with breathing and moving the tailbone with the head.')
on conflict (name) do update set
  activity = excluded.activity, sets = excluded.sets, reps = excluded.reps,
  description = excluded.description, howto = excluded.howto;
